# Generated by Django 3.0.5 on 2020-05-20 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('unique_id', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField()),
                ('thread_type', models.CharField(blank=True, choices=[('wih', 'Who Is Hiring'), ('fsf', 'Freelancer / Seeking Freelancer'), ('wwtbh', 'Who Wants To Be Hired')], max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=254)),
                ('content', models.TextField()),
                ('unique_id', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField()),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.Thread')),
            ],
        ),
    ]
